Consultorio/Controllers/AtencionController.cs
using Consultorio.BusinessLogic.Service;
using Consultorio.Entity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Consultorio.AppWeb.Controllers
{
    public class AtencionController : Controller
    {
        private readonly IAtencionService _atencionService;
        private readonly IMedicamentoService _medicamentoService;

        public AtencionController(IAtencionService atencionService, IMedicamentoService medicamentoService)
        {
            _atencionService = atencionService;
            _medicamentoService = medicamentoService;
        }
        public async Task<IActionResult> Index()
        {
            var atenciones = await _atencionService.GetAll();
            return View(atenciones);
        }
        public IActionResult DetalleAtencion(string strAtencion)
        {
            Atencion atencion = JsonConvert.DeserializeObject<Atencion>(strAtencion);
            return View(atencion);
        }
        public async Task<IActionResult> ResumenAtencion(int idAtencion)
        {
            var atencion = await _atencionService.GetOne(idAtencion);
            return View(atencion);
        }
        [HttpGet]
        public async Task<IActionResult> ObtenerMedicamentos()
        {
            var medicamentos = await _medicamentoService.GetAll();
            return Json(medicamentos);
        }
        [HttpPost]
        public async Task<IActionResult> GuardarAtencion(DateTime? FechaAtencion, string DniPaciente)
        {
            int idAtencion = await _atencionService.Insert(DniPaciente, FechaAtencion);
            return Json(idAtencion);
        }
        [HttpPost]
        public async Task<IActionResult> GuardarDiagnostico([FromBody] DiagnosticoEntity diagnostico)
        {
            bool resultado = await _atencionService.InsertDiagnostico(diagnostico);
            return Json(resultado);
        }
        [HttpPost]
        public async Task<IActionResult> GuardarTratamiento([FromBody] Tratamiento tratamiento)
        {
            bool resultado = await _atencionService.InsertTratamiento(tratamiento);
            return Json(resultado);
        }
        [HttpPost]
        public async Task<IActionResult> GuardarMedicamento([FromBody] MedicamentoAtencion medicamento)
        {
            bool resultado = await _atencionService.InsertMedicamento(medicamento);
            return Json(resultado);
        }

    }
}

Consultorio/Controllers/PacienteController.cs
using Consultorio.BusinessLogic.Service;
using Consultorio.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Security.Claims;

namespace Consultorio.AppWeb.Controllers
{
    [Authorize]
    public class PacienteController : Controller
    {
        private readonly IPacienteService _pacienteService;

        public PacienteController(IPacienteService pacienteService)
        {
            _pacienteService = pacienteService;
        }
        private string ObtenerDniClaim()
        {
            var usuario = HttpContext.User;
            return usuario.FindFirstValue("dni");
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            string dniUsuario = ObtenerDniClaim();
            var paciente = await _pacienteService.GetAll(dniUsuario);

            return View(paciente);
        }
        [HttpPost]
        public async Task<IActionResult> GuardarPaciente([FromBody] Paciente paciente)
        {
            string dniUsuario = ObtenerDniClaim();
            paciente.DniUsuario = dniUsuario;

            if (paciente == null)
                return Json(new Respuesta() { Mensaje = "Todos los campos son obligatorios" });

            return Json(await _pacienteService.SavePaciente(paciente));
        }
        [HttpGet]
        public async Task<IActionResult> Atencion(string dni)
        {
            string dniUsuario = ObtenerDniClaim();
            var paciente = await _pacienteService.GetOne(dni, dniUsuario);
            return View(paciente);
        }
        [HttpGet]
        public async Task<IActionResult> ObtenerPaciente(string dniPaciente)
        {
            string dniUsuario = ObtenerDniClaim();
            var paciente = await _pacienteService.GetOne(dniPaciente, dniUsuario);
            return Json(paciente);
        }
    }
}

Consultorio/Views/Paciente/Atencion.cshtml
@model Consultorio.Entity.Paciente

<div class="container">
    <form id="formAtencion">
        <fieldset class="mt-3">
            <legend>Datos Paciente</legend>
            <div class="row">
                <div class="col-md-6">
                    <label for="recipient-name" class="col-form-label">DNI Paciente:</label>
                    <input type="text" class="form-control" id="dni" value="@Model.DNI" readonly>
                </div>
                <div class="col-md-6">
                    <label for="recipient-name" class="col-form-label">Nombre Paciente:</label>
                    <input type="text" class="form-control" id="nombre" value="@Model.Nombre @Model.ApellidoPaterno @Model.ApellidoMaterno" readonly>
                </div>
            </div>
        </fieldset>
        <fieldset class="mt-3">
            <legend>Datos Atención</legend>
            <div class="row">
                <div class="col-md-6">
                    <label for="recipient-name" class="col-form-label">Fecha Atención:</label>
                    <input type="date" class="form-control" id="fechaAtencion">
                </div>
                <div class="col-md-6">
                    <label for="recipient-name" class="col-form-label">Hora Atención:</label>
                    <input type="time" class="form-control" id="horaAtencion">
                </div>
            </div>
        </fieldset>
        <div class="mt-5">
            <div class="d-flex justify-content-end">
                <button type="button" class="btn btn-success" id="crearAtencion">Crear atención y continuar</button>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $("#crearAtencion").click(function () {
                let atencion = {
                    FechaAtencion: $("#fechaAtencion").val() + " " + $("#horaAtencion").val(),
                    DniPaciente: $("#dni").val()
                };
                $.ajax({
                    url: '@Url.Action("GuardarAtencion", "Atencion")', // URL del servidor que proporciona los datos
                    //contentType: "application/json; charset=utf-8",
                    type: "POST",
                    //data: JSON.stringify(atencion) // Parámetro que deseas pasar al servidor
                    data: { fechaAtencion: $("#fechaAtencion").val() + " " + $("#horaAtencion").val(), dniPaciente: $("#dni").val() } // Parámetro que deseas pasar al servidor
                })
                    .done(function (idAtencion) {

                        if (idAtencion > 0) {
                            atencion.IdAtencion = idAtencion;
                            var objetoCodificado = encodeURIComponent(JSON.stringify(atencion));
                            window.location.href = '/Atencion/DetalleAtencion?strAtencion=' + objetoCodificado;
                        }
                        else {
                            Swal.fire({
                                title: "Error",
                                text: "Ocurrió un error en el guardado",
                                icon: "error"
                            });
                        }
                    });
            });
        })
    </script>
}

Consultorio/Views/Paciente/Index.cshtml
@model IEnumerable<Consultorio.Entity.Paciente>

<div class="container">
    <div class="col-md-12">
        <button class="btn btn-success" id="openModal">Nuevo Paciente</button>
    </div>
    <div class="col-md-12 mt-3">
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>DNI</td>
                    <td>Nombre</td>
                    <td>Apellidos</td>
                    <td>Correo</td>
                    <td>Fecha Nacimiento</td>
                    <td>Acciones</td>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count() > 0)
                {
                    @foreach (var paciente in Model)
                    {
                        <tr>
                            <td>@paciente.DNI</td>
                            <td>@paciente.Nombre</td>
                            <td>@paciente.ApellidoPaterno @paciente.ApellidoMaterno</td>
                            <td>@paciente.Correo</td>
                            <td>@paciente.FechaNacimiento?.ToString("dd-MM-yyyy")</td>
                            <td>
                                <a class="btn btn-success" onclick='obtenerPaciente(@paciente.DNI)'>Editar</a>
                                <a class="btn btn-primary" href="@Url.Action("Atencion", "Paciente", new { dni = paciente.DNI })">Atender</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="5">
                            <div class="alert alert-info text-center">
                                <p>No hay pacientes registrados</p>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="modalEditarCrear" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="tituloModal">Paciente</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="formPaciente">
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">DNI:</label>
                        <input type="text" class="form-control" name="DNI" id="dni" required>
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Nombre:</label>
                        <input type="text" class="form-control" name="Nombre" id="nombre" required>
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Apellido Paterno:</label>
                        <input type="text" class="form-control" name="ApellidoPaterno" id="apellidoPaterno" required>
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Apellido Materno:</label>
                        <input type="text" class="form-control" name="ApellidoMaterno" id="apellidoMaterno" required>
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Correo:</label>
                        <input type="text" class="form-control" name="Correo" id="correo" required>
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Fecha Nacimiento:</label>
                        <input type="date" class="form-control" name="FechaNacimiento" id="fechaNacimiento" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button class="btn btn-primary" id="guardarPaciente" type="button">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        function limpiarModal() {
            $("#dni").val("");
            $("#nombre").val("");
            $("#apellidoPaterno").val("");
            $("#apellidoMaterno").val("");
            $("#correo").val("");
            $("#fechaNacimiento").val("");
        }
        function obtenerPaciente(dniPaciente) {
            $.ajax({
                type: "GET",
                url: '@Url.Action("ObtenerPaciente")', // URL del servidor que proporciona los datos
                data: { dniPaciente: dniPaciente }, // Parámetro que deseas pasar al servidor
                dataType: "json", // Tipo de datos esperados en la respuesta
                success: function (data) {
                    let fechaNacimiento = new Date(data.fechaNacimiento);
                    $("#dni").val(data.dni);
                    $("#nombre").val(data.nombre);
                    $("#apellidoPaterno").val(data.apellidoPaterno);
                    $("#apellidoMaterno").val(data.apellidoMaterno);
                    $("#correo").val(data.correo);
                    $("#fechaNacimiento").val(fechaNacimiento.toISOString().slice(0, 10));
                    $("#modalEditarCrear").modal('show');
                },
                error: function (xhr, status, error) {
                    // Manejar errores de la solicitud AJAX
                    console.error("Error al cargar los datos:", status, error);
                }
            });
        }

        $(document).ready(function () {
            $("#openModal").click(function () {
                limpiarModal();
                $("#modalEditarCrear").modal('show');
            });
            $("#guardarPaciente").click(function () {
                paciente = {
                    DNI: $("#dni").val(),
                    Nombre: $("#nombre").val(),
                    ApellidoPaterno: $("#apellidoPaterno").val(),
                    ApellidoMaterno: $("#apellidoMaterno").val(),
                    Correo: $("#correo").val(),
                    FechaNacimiento: $("#fechaNacimiento").val()
                };

                $.ajax({
                    url: '@Url.Action("GuardarPaciente", "Paciente")', // URL del servidor que proporciona los datos
                    contentType: "application/json; charset=utf-8",
                    type: "POST",
                    data: JSON.stringify(paciente) // Parámetro que deseas pasar al servidor
                })
                    .done(function (respuesta) {

                        if (respuesta.resultado) {
                            location.reload();
                        }
                        else if (!respuesta.resultado && Boolean(respuesta.mensaje)) {
                            Swal.fire({
                                title: "Advertencia",
                                text: respuesta.mensaje,
                                icon: "warning"
                            });
                        }
                        else {
                            Swal.fire({
                                title: "Error",
                                text: "Ocurrió un error en el guardado",
                                icon: "error"
                            });
                        }
                    });
            });
        })
    </script>
}